### ISSUE TITLE
Add requirements.txt and GitHub workflow for CI/CD

### ISSUE THREAD

**Issue by Adesoji1** [llmware-ai/llmware#103]
Use pipreqs to generate requirements.txt
Create a yaml file for that or I will make a PR for this

**Comment by turnham** [comment]
There is already a carefully curated [requirements.txt](https://github.com/llmware-ai/llmware/blob/main/llmware/requirements.txt) in the repo, and for our Pypi wheels the dependencies are captured in [setup.py](https://github.com/llmware-ai/llmware/blob/main/setup.py).  What problem or gap would pipreqs be addressing?

And what sort of GitHub workflow are you suggesting?  llmware contains some native code dependencies that are not open source (our PDF and Office file parsers) and so our CI/CD for the building and packaging of llmware for delivery to PyPi happens in-house.

**Comment by Adesoji1** [comment]
Alright, totall understood. Thanks
