### ISSUE TITLE
examples/Models /using_openvino_models.py -> "Directory missing" error

### ISSUE THREAD

**Issue by andytolle** [llmware-ai/llmware#1104]
To replicate the error:
- On windows (10 or 11): Delete "c:\users\<user>\llmware_data\model_repo" directory
- Run the openvino example "examples/Models /using_openvino_models.py"
- Notice how the example doesn't run: The user gets an error (saying that something is missing: this directory).

The user needs to then first manually create the directory. Then the example runs fine.

A quick fix is either 
- Check for the directory and create it, if it doesn't exist (would probably be nice to do it in the library)
- or catching and interpreting the error in the example and programmatically create the directory if needed

**Comment by doberst** [comment]
@andytolle - great catch - and yes, this is a bug - missing defensive code in a path specific to loading the external tokenizer used with OpenVINO models (if this is first use of llmware).    Will be fixed later today.   Appreciate you sharing this.... keep the feedback coming!  :).  kind regards - Darren
