### ISSUE TITLE
Llmware is not working in Sub linux system Ubuntu under Windows 11

### ISSUE THREAD

**Issue by AlbelTec** [llmware-ai/llmware#115]
Hi 

I tried to do some experiments with Parser() (first into json and then into memory) but in both cases I'm ending up with error : Fault Segmentation. 
I presume this has been already reported but seems no fix has been released so far. 

kr,

**Comment by JessBerl** [comment]
Hi @AlbelTec - please try the work around described in https://github.com/llmware-ai/llmware/discussions/48.

**Comment by AlbelTec** [comment]
Hi @JessBerl 
Actually I did use : `ulimit -s 32768000`
but still getting the error :

```
> Parsing folder: data...
Segmentation fault
(llmware) albel@Thinkpad:~/llmware$ 
```

here is my code :

```
def parsing_pdf():
    # Create a parser
    parser = Parser()

     # Parse entire folder to json
    print (f"\n > Parsing folder: {dataDir}...")

    pdf_parsed_output = Parser().parse_one_pdf("/home/albel/llmware/data/", "Large Language Models.pdf")
    page_number = pdf_parsed_output[0]["master_index"]
    block_text = pdf_parsed_output[0]["text"]
    print(f"\nFirst block found on page {page_number}:\n{block_text}")

    # Parse to json
    #blocks  = parser.ingest_to_json(dataDir)
    # print (f"Total Blocks: {len(parser.parser_output)}")
    # print (f"Files Parsed:")
    # for processed_file in blocks["processed_files"]:
    #     print(f"  - {processed_file}")
    
parsing_pdf()
```

**Comment by turnham** [comment]
Hi @AlbelTec I just tried on WSL2 (Windows 10) and was able to get things working with:
```
ulimit -s 160000
```
(The higher 32768000 value seems to be only required when running Linux in a container on Mac)
  
However, in your case it looks like the ulimit setting might not be taking effect at all.  You may be hitting this issue:

[https://github.com/microsoft/WSL/issues/633](https://github.com/microsoft/WSL/issues/633)

Can you try the workaround suggested at the bottom of that issue?:

```
sudo prlimit --stack=unlimited --pid $$; ulimit -s unlimited
```

**Comment by AlbelTec** [comment]
@turnham Thanks! finally it worked. Actually ulimit was static with 8192 as value. it turned out that with `prlimit` with root privileges it assign an `unlimited` as value and the issue gone.
