### ISSUE TITLE
Install on Ubuntu 23.10

### ISSUE THREAD

**Issue by JeremyBickel** [llmware-ai/llmware#124]
Howdy. This looks like a great program. I wish I could try and see, but I'm on ubuntu 23.10, and there's no easy way for me to install anything under python 3.11. I tried before contacting you - I tried hard - but I just couldn't find a way to install it. Is it absolutely necessary not to use python 3.11? I have that.

Thank you.

**Comment by doberst** [comment]
@JeremyBickel - thanks for your feedback.   We just dropped an update today which we tested on 3.11 on Ubuntu, and it all looks good!     Please pull again from the repo - or pip install llmware==0.1.9 - please let us know if you experience any issues.

**Comment by JeremyBickel** [comment]
This is working after your update. Thanks. I look forward to working with this.
