### ISSUE TITLE
Example Google colab notebooks to show applocations of optimized models

### ISSUE THREAD

**Issue by timtensor** [llmware-ai/llmware#156]
Hi it would be great to have some example colab notebooks for RAG demonstrations and used cases ? It would help how to maybe see other RAG applications such as llama index for example 

Thanks in advance

**Comment by gongwork** [comment]
@timtensor  I start to learn `llmware` and recreate jupyter notebook files from the corresponding to example python script

**Comment by timtensor** [comment]
Looking forward , especially for open sourced 7b models such as Mistral ( quantized or similar ) which does not consume high RAM

**Comment by doberst** [comment]
We have added Notebook examples into the Examples section of the repository, including Google Collab examples.
