### ISSUE TITLE
Vector DB:  Add support for Chroma

### ISSUE THREAD

**Issue by JessBerl** [llmware-ai/llmware#17]
Expand Vector DB support to include Chroma.  

Milvus and Pinecone implementations in the embeddings.py can be used as a guide.

Scope includes:
Updating  LLMWareConfig, EmbeddingHandler
Creating an Embedding class specific to Chroma
Test scripts and example code

**Comment by kokobhara** [comment]
Hi @JessBerl , I'm new to both open-source and LLM-based development. Can I take this up? I'd be more than happy to contribute to this project.
Thanks!

**Comment by JessBerl** [comment]
Hi @kokobhara, we are happy to have you contribute to llmware and take up adding support for Chroma.  If you haven't seen our [contributor's guide](https://github.com/llmware-ai/llmware/blob/main/CONTRIBUTING.md) yet, please take a look.  And if you have any questions, please ask them here - we're happy to help!   Thank you!!

**Comment by kokobhara** [comment]
Sure, I'll get started right away. Thank you so much!

**Comment by jeffchuber** [comment]
+1 🫡

**Comment by MacOS** [comment]
Hi guys,

I'm happy to contribute to this issue too (I did #22). Let me know how, and if I can help.

**Comment by MacOS** [comment]
Hi guys,

I just created a pull request #357 that adds support for chroma. Please have a look. In addition, I have three notes.

First, the ```embedding``` and ```config``` module need refactoring. There is a loft of boilerplate code that is unnecessarily repeated, for example.

Second, the embedding stores need be tested more thoroughly. I added a bunch of TODO to the chroma test case.

And finally, I hope I did not anger anyone by rushing forward.

**Comment by MacOS** [comment]
I think this issue can be closed, since my PR #357 has been merged.

My first point about refactoring should be carried over to another Issue.

**Comment by doberst** [comment]
CLOSED - Well done!
