### ISSUE TITLE
gpt-3.5-turbo-1106 and gpt-4-1106-preview support

### ISSUE THREAD

**Issue by shneeba** [llmware-ai/llmware#198]
Hi, sorry if this isn't the right place, however I can't seem to get the two new OpenAI models working. I get the following error:

```
Starting prompt with sources using model: gpt-3.5-turbo-1106
ERROR:root:error: OpenAI model inference produced error - This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

Starting prompt with sources using model: gpt-4-1106-preview
ERROR:root:error: OpenAI model inference produced error - This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
```

The other models (`gpt-4` etc) from OpenAI are working just these two don't and wanted to see performance / output. I checked the `models.py` file and they're listed there.

Awesome project by the way, _exactly_ what I was looking for.

**Comment by doberst** [comment]
Thanks for the feedback - and good catch - it was a bug - we were routing gpt-3.5-turbo-1106 and gpt-4-1106-preview to the "completions api" rather than the "chat api" 

I will put in a fix in a few minutes - and will paste into this chat so you can pick it up here directly if you prefer ....

**Comment by doberst** [comment]
models.py - line 920 - updated in the main branch - 
if self.model_name in ["gpt-3.5-turbo","gpt-4","gpt-4-1106-preview","gpt-3.5-turbo-1106"]:

Please check/confirm that this solves the issue.

**Comment by shneeba** [comment]
Perfect, thanks for the quick response and fix 👍

```
python .\testing.py "gpt-4-1106-preview" "2022-pepsico-annual-report.pdf" "What was the net revenue for 2022 compared to 2021?" "Net revenue"
Starting prompt with sources using model: gpt-4-1106-preview
- Context: 2022-pepsico-annual-report.pdf
- Prompt: What was the net revenue for 2022 compared to 2021?
- LLM Response:
The net revenue for 2022 was $86,392 million compared to $79,474 million in 2021.
```
