### ISSUE TITLE
Assigning a "base_url"

### ISSUE THREAD

**Issue by Francisco-Reveriano** [llmware-ai/llmware#204]
Hello Team. Love the library. I am working with the Prompt().load_model() function. 

I can assign an api_key but it doesn't allow me to assign a "Bare_url" to use that key. 

Would appreciate any help.

**Comment by dtthanh1971** [comment]
If you use openai version <1.0

setup OPENAI_BASE_URL = "your base url"

Else (openai version == 0.27.7)
setup OPENAI_API_BASE = "your base url"  # http://127.0.0.1:8000 my case using litellm as a Open AI proxy server


LLMware wappaped openai in its llm model.

Import openai  (version 0.27.7)

import openai
openai.api_base=os.environ.get("OPENAI_BASE_URL ") or
or 
openai.api_base=os.environ.get("OPENAI_API_BASE")

**Comment by doberst** [comment]
@dtthan1971 - FYI, we added OpenChat support last week.   This should enable you to support this use case.    Please check out the example in Examples/Models in the file: using-open-chat-models.py -  [link](https://www.github.com/llmware-ai/llmware/blob/main/examples/Models/using-open-chat-models.py)
