### ISSUE TITLE
ERROR:root:error:  to use prompt_with_source, there must be a loaded source - try '.add_sources' first

### ISSUE THREAD

**Issue by vdeeplearn** [llmware-ai/llmware#207]
What is causing the below issue,  I am not finding the  method '.add_sources' in prompt object, 
I am trying the following script, llmware/examples/Getting_Started$ python working_without_a_database.py
Analyzing disease-Sample file 3.pdf
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(41)analyze_contracts_on_the_fly()
-> source = prompter.add_source_document(contracts_path, contract, query="Diseases")
(Pdb) c
ERROR:root:error:  to use prompt_with_source, there must be a loaded source - try '.add_sources' first
Traceback (most recent call last):
  File "/home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py", line 317, in <module>
    analyze_contracts_on_the_fly(model_name)
  File "/home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py", line 48, in analyze_contracts_on_the_fly
    print("LLM Response: " + response["llm_response"])
                             ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'llm_response'
(privategpt) appuser@ip-10-50-2-248:~/llama/RAG/llmware/examples/Getting_Started$ python working_without_a_database.py

 > Loading the llmware sample files...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

 > Analyzing contracts with prompt: 'What is the Diseases in the document?'
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(34)analyze_contracts_on_the_fly()
-> if contract != ".DS_Store":
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(64)analyze_contracts_on_the_fly()
-> prompter.save_state()
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(32)analyze_contracts_on_the_fly()
-> for i, contract in enumerate(os.listdir(contracts_path)):
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(33)analyze_contracts_on_the_fly()
-> import pdb;pdb.set_trace()
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(34)analyze_contracts_on_the_fly()
-> if contract != ".DS_Store":
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(36)analyze_contracts_on_the_fly()
-> print (f"\n > Analyzing {contract}")
(Pdb) n

 > Analyzing disease-Sample file 3.pdf
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(41)analyze_contracts_on_the_fly()
-> source = prompter.add_source_document(contracts_path, contract, query="Diseases")
(Pdb) n
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(46)analyze_contracts_on_the_fly()
-> responses = prompter.prompt_with_source(prompt_text, prompt_name="number_or_none")
(Pdb) n
ERROR:root:error:  to use prompt_with_source, there must be a loaded source - try '.add_sources' first
> /home/appuser/llama/RAG/llmware/examples/Getting_Started/working_without_a_database.py(47)analyze_contracts_on_the_fly()
-> import pdb;pdb.set_trace()
(Pdb)

**Comment by doberst** [comment]
please try the method:   ".add_source_document" which takes as input a file_path, and a file_name, and then parses the document and attaches to the prompt.   We will update the exception too.    Please let us know if that fixes the issue.

**Comment by doberst** [comment]
Sorry, responded too quickly - let me go thru the script too - and see if we can replicate the error

**Comment by doberst** [comment]
Ok - got it!   :).   We have replicated the error.   The script works fine with the .add.source_document method if the filter is the original script "base salary" - but if you replace with "diseases" then it is returning an empty source - e.g.,source -  {'text_batch': [], 'metadata_batch': [], 'batches_count': 0} since the word "diseases" is not found in the parsed text.   When .prompt_with_source hits this empty source, it throws the error as the intention is that there will be a non-empty context passage included in the prompt.    Two work-arounds:

1.   In the script, you could add a check for an empty source, and then not prompt, e.g., "No evidence found to support the question."   You can print out the sources output and you will see the dictionary above, with sources["text_batch"] as empty and/or

2.  We will take a look at better exception handling of this case in the prompt_with_source method so that it is not necessarily breaking ...  if you have a specific recommendation on the behavior you would prefer, let us know.

Appreciate you raising this issue.   Let us know if this works for you.

**Comment by shneeba** [comment]
This is something I've noticed as well and I've implemented a rudimentary check in my script if no text is found:

```
    # Attempt to attach the document as a source
    try:
        prompter.add_source_document(file_path, local_file, query=user_query)
    except Exception as e:
        print(f"Error adding source document: {e}")
        return

    # Run the inference
    try:
        response = prompter.prompt_with_source(prompt=user_prompt)
    except Exception as e:
        print(f"Error during prompting: {e}")
        return

    # Check if response is empty or not in expected format
    if not response or 'llm_response' not in response[0] or not response[0]['llm_response'].strip():
        print("No text found, try a different query")
    else:
        # Display the response
        response_display = response[0]["llm_response"]
        print(f"- Context: {local_file}\n- Prompt: {user_prompt}\n- LLM Response:\n{response_display}")

    # Clear the source materials after use
    prompter.clear_source_materials()
```

This gives you a result like so:

```
stdout: Starting prompt with sources using model: gpt-4-1106-preview
- Context: CBP-7692.pdf
- Prompt: What is a referendum
- LLM Response:
A referendum is a process or principle of referring an important political question, such as a proposed constitutional change, to be decided by a general vote of the entire electorate; a vote taken by referendum.

stderr: 
stdout: Starting prompt with sources using model: gpt-4-1106-preview
No text found, try a different query

stderr: ERROR:root:error:  to use prompt_with_source, there must be a loaded source - try '.add_sources' first
```

Showing the user that no text was found would be preferred.

**Comment by doberst** [comment]
Improved handling of this error has been added and merged into the main branch.   Thanks for your feedback!
