### ISSUE TITLE
Vector DB:  add support for Redis

### ISSUE THREAD

**Issue by JessBerl** [llmware-ai/llmware#21]
Expand Vector DB support to include Redis.  

Milvus and Pinecone implementations in the embeddings.py can be used as a guide.

Scope includes:
Updating  LLMWareConfig, EmbeddingHandler
Creating an Embedding class specific to Redis
Test scripts and example code

**Comment by JessBerl** [comment]
Closing for now until there is more interest in support for this db.

**Comment by upjabir** [comment]
@JessBerl If the request is still open. Am happy to contribute
