### ISSUE TITLE
error encountered running docs2vecs_with_milvus-rag.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#210]
I encountered an error while running docs2vecs_with_milvus-rag.py
The problem is there is no response from the model and the llm_response key is not available in the dictionary.

   Contract Name:  1 Amphitrite EXECUTIVE EMPLOYMENT AGREEMENT.pdf
   ERROR:root:error:  to use prompt_with_source, there must be a loaded source - try '.add_sources' first
   Traceback (most recent call last):
      File "d:\home\john\Projects\llmware-main\examples\Embedding\docs2vecs_with_milvus-rag.py", line 92, in <module>        
         rag(user_selected_name)
      File "d:\home\john\Projects\llmware-main\examples\Embedding\docs2vecs_with_milvus-rag.py", line 82, in rag
         print("\nupdate: llm answer - ", resp["llm_response"])
                                     ~~~~^^^^^^^^^^^^^^^^
      KeyError: 'llm_response'

I added this check for llm_response  at line 81 in docs2vecs_with_milvus-rag.py on my system and it ran without errors.

for resp in response:
          if 'llm_response' in resp:
              print("\nupdate: llm answer - ", resp["llm_response"])
          else:
              print("\nupdate: llm answer - No Response")

John

**Comment by doberst** [comment]
Example updated - thanks for catching this!
