### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by mjspeck** [llmware-ai/llmware#219]
Obviously this would be pretty big for a single issue but that fact that most methods don't seem to have docstrings is troubling. The tutorials you have are very helpful but they're not a full replacement for actual docstrings, type annotations, etc. which make it much easier to build using llmware. Happy to contribute as well, but that would require knowing what docstring format y'all prefer and other style guide standards.

**Comment by rahpandey1** [comment]
I can also contribute

**Comment by doberst** [comment]
@mjspeck and @rahpandey1 - appreciate this feedback.   We have taken initial steps on docstrings - very simple and lightweight through the main code.   Realize that there is a lot more to do here - would welcome ideas and help to improve on this starting point.    On type annotations for Python, we have debated it internally quite a bit - and right now, would probably side with prioritizing docstrings as well as core documentation.

**Comment by MacOS** [comment]
I'm also happy to contribute on this!

**Comment by MacOS** [comment]
I would suggest to add docstrings systematically in the following order, where one point is one issues and hence one pull request.
1. Add docstrings to all modules,
2. Add docstrings to all classes and functions,
3. Add docstrings to all methods and class methods.

**Comment by MacOS** [comment]
I submitted the pull request #406 that adds docstrings to all modules, and the package.

After this PR has been merged, we can move forward by adding docstrings to the classes.

**Comment by MacOS** [comment]
I submitted the pull request #449 to add class docstrings to four modules. I decided to split up adding class docstrings, since one pull request that adds class docstrings to all classes would be too large.

**Comment by mjspeck** [comment]
Sorry I haven't been active on this. I'll take a look in the next week at what I can contribute.

**Comment by MacOS** [comment]
@mjspeck No worries. Please post first on what you are working before you start. I would recommend that you pick on module and add class docstrings to all classes there, and then submit this as a PR. Otherwise, the PR gets too big.

**Comment by doberst** [comment]
Docstrings substantially complete throughout the code base.  If specific request, we can open up as a new issue.
