### ISSUE TITLE
Vector DB:  Add support for Neo4j

### ISSUE THREAD

**Issue by JessBerl** [llmware-ai/llmware#22]
Expand Vector DB support to include Neo4j.  

Milvus and Pinecone implementations in the embeddings.py can be used as a guide.

Scope includes:
Updating  LLMWareConfig, EmbeddingHandler
Creating an Embedding class specific to Neo4j
Test scripts and example code

**Comment by MacOS** [comment]
Hi all,

I'm working on this issue and would submit a pull request soon, roughly within the next week. Can someone please assign me to this issue so no one else wastes time on it? Thank you!

**Comment by doberst** [comment]
Hi MacOS - appreciate your contribution - BTW, please check the updated EmbeddingHandler and embedding classes - there have been some recent updates in terms of support for other vector DBs - should provide a good template and starting point for Neo4j ... Hope things are progressing well!

**Comment by MacOS** [comment]
Of course! Happy to help out.

I started, but could not finish in time before Christmas because of a busy week. Depending on how busy the holidays are, I will come back to it either before or after new years.

I will open a pull request once it is good enough for a first look.

**Comment by MacOS** [comment]
Just a quick heads up: I started to work on it, and I'm 70-80% done with it.

**Comment by MacOS** [comment]
I have a question.

Neo4j support vector indexes since 5.11.  I plan to check which version is running and raise a ```ValueError``` in case this is not true, similar to what is done [here](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/neo4j_vector.py#L279). Is this ok?

**Comment by MacOS** [comment]
Hi guys,

i just opened a pull-request - #310 . Please have a look. I should address everything @JessBerl listed, plus the docker image for Neo4j. However, this is not 100% done yet because I'm unsure how you want to handle that.

**Comment by doberst** [comment]
@MacOS - GREAT JOB - BIG LIFT .... Thank you.    🙏 🙏 🙏  ... Your code:   🔥 🔥 🔥  .... Keep the good stuff coming!

**Comment by MacOS** [comment]
Thank you, @doberst! Happy to help out, and contribute again. I already offered my help for #17.
