### ISSUE TITLE
llmware always creates collection in 'default' vector database

### ISSUE THREAD

**Issue by virunew** [llmware-ai/llmware#249]
It seems that currently the framework does not have option to provide own database name for vector database . All collections are created in 'default' database. This is an issue because if I run-tests.py, the 'default' database is cleared and all collections are deleted , this results in loss of all data. So we need an option for providing a non 'default' database name for vector database as a parameter while calling install_new_embeddings() function in embeddings.py

I have only used Milvus  vector databse , which has this hierarchy of database->collection. not sure about other vector databases

**Comment by doberst** [comment]
Great point - agree 100%.    Will provide a fix - and try to get in today's update.   Will revert back.   Thanks for catching this!

**Comment by doberst** [comment]
Hi Virendra - thanks again for highlighting this - apologies that our attempts to fix it 'crossed' last night - we were both keen to resolve this issue!   :).   I will close the issue, but let's keep an open dialog as I would like to keep working together on enhancing the robustness of our configurations to really scale up large Milvus instances (as well as other key endpoints) ...   Best wishes for a wonderful 2024 up ahead - and look forward to collaborating in the llmware community!

**Comment by virunew** [comment]
Thanks Darren! and wish you a great and fulfilling new year too :)
