### ISSUE TITLE
remove .DS_Store from llmware_data\sample_files

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#257]
Can you remove the .DS_Store file from the llmware_data\sample_files directories.
This is a file for mac directory instructions and chokes several examples when run on Windows platform.

I found 3 of them
1) llmware_data\sample_files\.DS_Store
2) llmware_data\sample_files\Agreements\.DS_Store
3) llmware_data\sample_files\Invoices\.DS_Store

Thanks,

John

**Comment by doberst** [comment]
Agree 100% - really annoying - we zipped the files on a Mac - and the archive utility seems to have added them.   Give us a couple of days - we will re-zip on Linux/Windows and hopefully that will solve it.

BTW- Happy new year & All the best for 2024!

**Comment by doberst** [comment]
@JEHollierJr - the sample files were updated to exclude the .DS_Store for Windows and Linux.
