### ISSUE TITLE
typo in gpt-3.5-turbo model name in getting_started\working_without_a_database.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#258]
The model name has a typo 

Line 324
    #   feel free to replace with any other model
    model_name = "gpt-3.5.-turbo"

remove the dot after 3.5 

line 324
    #   feel free to replace with any other model
    model_name = "gpt-3.5-turbo"

**Comment by doberst** [comment]
Done - good catch!
