### ISSUE TITLE
Max token limit

### ISSUE THREAD

**Issue by rishi1007** [llmware-ai/llmware#274]
Hi all. I wanted to know what is the max-token limits for the open-source models here.
Thanking in advance.

**Comment by NYDocutest** [comment]
Hi Rishi,
The max-token limits are based on the model's context window max which is generally either 2048 or 4096 for the smaller models but is larger for Open AI for instance.

**Comment by rishi1007** [comment]
Anywhere is there a documentation mentioning the token limit for specifically the open-source models?
