### ISSUE TITLE
issue with library name in dual_pass_custom_filter.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#298]
There is an issue with the libray name in examples/Retrieval/dual_pass_custom_filter.py 

if __name__ == "__main__":
    #library_name = "UN-Resolutions-500"
    library_name = "un_resolutions500"

the uncommented name is the correct one as created from examples.

This example expects the library to already be created.

**Comment by doberst** [comment]
good catch - fixed
