### ISSUE TITLE
update_embedding_status fails for non 'llmware' account name

### ISSUE THREAD

**Issue by virunew** [llmware-ai/llmware#301]
update_embedding_status fails for non 'llmware' account name because  update_embedding_status() function is not passed an account name. It still works for llmware account_name becuase that's the default param value but not for any custom account_name. Raising a a PR for this fix. Please check. Error I get is as below:

`File "/Users/tech9/repos/finrag/llmware/llmware/library.py", line 317, in update_embedding_status
    updater = LibraryCatalog(self).update_library_card(self.library_name, update_dict,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tech9/repos/finrag/llmware/llmware/library.py", line 819, in update_library_card
    account_name=self.account_name).update_library_card(library_name,
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tech9/repos/finrag/llmware/llmware/resources.py", line 238, in update_library_card
    return self._writer.update_library_card(library_name, update_dict, lib_card, delete_record=delete_record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tech9/repos/finrag/llmware/llmware/resources.py", line 393, in update_library_card
    embedding_list = lib_card["embedding"]
                     ~~~~~~~~^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str()`

**Comment by doberst** [comment]
Thanks for fixing this - it has been merged!   👍
