### ISSUE TITLE
Duplicate check fails for OCR docs 

### ISSUE THREAD

**Issue by virunew** [llmware-ai/llmware#309]
duplicate check fails for OCR docs , the reason is: 

 There is no use of Parser()._collater in Parser().parse_pdf_by_ocr_images() and many other functions in parser class , which leads to duplicate file ingestion. Some other functions like Parser().ingest() use _collator which results in correct duplicate check

**Comment by doberst** [comment]
@virunew - agree with you 100% that it was definitely an area that needed attention.   I have integrated several changes into the Parser class that give better options and controls around duplicate checking as well as copying files into library when using one of the python-based parsers "a la carte" ... check it out and let me know what you think.  We can keep iterating and improving on this .... will be integrating into the next pip install too later today (0.2.1) ...

**Comment by doberst** [comment]
Closing the issue, as resolved in 0.2.1 - please open a new issue if any recurring problems ...
