### ISSUE TITLE
Ollama - Local LLM Support

### ISSUE THREAD

**Issue by AbrahimZaman360** [llmware-ai/llmware#312]
Want to use Local LLM through Ollama

**Comment by doberst** [comment]
@AbrahimZaman360 - thanks for this feedback.   Great idea, and we agree.   We have added Ollama support in the main branch in the repo, as well as the most recent pip release (0.2.1) ... There is a nice example in examples/Models on how to use ollama models- as well as a video on our Youtube channel.   Appreciate bringing good ideas - and please keep them coming!  👍
