### ISSUE TITLE
dragon-yi-6b-gguf model doesn't download anymore

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#333]
I did a clean install with llmware v1.15 and now the dragon-yi-6b-gguf model doesn't install.
I am running on windows 11 pro.  The dragon-Llama-2-gguf and dragon-Mistral-7b-gguf models download as expected.

I ran the example dragon_gguf_fast_start.py, dragon-yi-6b-gguf is the model by default, and I see the following error:

PS D:\home\john\Projects\llmware-main> & C:/Users/jehol/AppData/Local/Programs/Python/Python311/python.exe d:/home/john/Projects/llmware-main/examples/Models/dragon_gguf_fast_start.py

 > Loading RAG dataset 'llmware/rag_instruct_benchmark_tester'...

 > Loading model 'llmware/dragon-yi-6b-gguf'
Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Models\dragon_gguf_fast_start.py", line 58, in <module>
    output = run_test(model_name,ds)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\home\john\Projects\llmware-main\examples\Models\dragon_gguf_fast_start.py", line 26, in run_test
    prompter = Prompt().load_model(model_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\prompts.py", line 168, in load_model
    self.llm_model = self.model_catalog.load_model(gen_model, api_key=self.llm_model_api_key)      
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\models.py", line 750, in load_model
    my_model = my_model.load_model_for_inference(loading_directions, model_card=model_card)        
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\models.py", line 3218, in load_model_for_inference
    raise ValueError(f"Model path '{model_file}' doesn't exist.")
ValueError: Model path 'C:\Users\jehol\llmware_data\model_repo\dragon-yi-6b-gguf\dragon-yi-6b-q4_k_m.gguf' doesn't exist.
PS D:\home\john\Projects\llmware-main>

**Comment by doberst** [comment]
Working on this - it does look like it is an issue with the HF symlinks ...  I just tested on a Windows machine, and per the Discord recommendation, if you set local_dir_use_symlinks=False when loading the model, then it is working.   Will be testing on Linux and Mac too - and then integrating the change in the main branch by EOD.   This will save the full set of model files in the local directory in model_repo path.

**Comment by doberst** [comment]
@JEHollierJr - fix has been merged - resolves the issue in our testing - let me know if you still have any issues.
