### ISSUE TITLE
LLMfx has no function 'category'

### ISSUE THREAD

**Issue by e-ave** [llmware-ai/llmware#413]
Following the llmware/blob/main/examples/SLIM-Agents/README.md to https://www.huggingface.co/llmware/slim-category-tool (by the way the readme says wwww instead of www)

We find on the huggingface page that you can do 
```
llm_fx = LLMfx()
llm_fx.load_tool("category")
response = llm_fx.category(text) 
```

This works for every other SLIM tool; however, `category` is not a valid function, nor any other similarly named function.

The only way I could get the category tool to work with LLMfx by using `llm_fx.exec_multitool_function_call(tool_type_list=["category"], text="Query string")`

I am using llmware 0.2.2, but I also searched the github repo and did not find any such function

**Comment by doberst** [comment]
@e-ave - good catch - we are fixing this - should be merged into the main repo today.
