### ISSUE TITLE
Can't decode character in setup.py during pip install

### ISSUE THREAD

**Issue by jcalebsmith** [llmware-ai/llmware#42]
I'm getting the following issue when trying to install on Python 3.9 and 3.10 with version 0.1.4 in pip

`pip install llmware
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting llmware
  Downloading llmware-0.1.4.tar.gz (608 kB)
     ---------------------------------------- 608.1/608.1 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\test\Local\Temp\pip-install-xvcskndt\llmware_f9aa6b83f25441099b7901721dfab793\setup.py", line 61, in <module>
          long_description = readme_file.read()
        File "C:\test\anaconda3\envs\llmware\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 9174: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.`

**Comment by turnham** [comment]
Hi @jcalebsmith.  From the error message (specifically the reference to "C:\test\Local\...") it looks like you're installing on Windows. Windows support is on our near term roadmap and we hope to have it soon.

**Comment by jcalebsmith** [comment]
Just noticed that! I'll give a try with WSL.
