### ISSUE TITLE
Cant find PDF Parser

### ISSUE THREAD

**Issue by Nuclear6** [llmware-ai/llmware#444]
platform info: 
<img width="1553" alt="image" src="https://github.com/llmware-ai/llmware/assets/49468241/a06b74c2-2c5c-4108-8df0-0f4a8508ee4f">
<img width="812" alt="image" src="https://github.com/llmware-ai/llmware/assets/49468241/5d3f28e9-5a40-46ab-8828-deea40d11422">

this is my problem:
<img width="1164" alt="image" src="https://github.com/llmware-ai/llmware/assets/49468241/6587dd2d-949e-48a2-9b83-a3b664a78dab">

**Comment by mupago** [comment]
@Nuclear6 I am also experiencing the same issue. This looks like a problem with the latest version of llmware itself and older versions don't have this problem as reported by my colleague. He got these scripts working fine for llmware v0.2.1 and v0.1.14 without any issues.

**Comment by mupago** [comment]
@doberst I am running it on #64~20.04.1-Ubuntu machine.

**Comment by doberst** [comment]
@mupago - thanks for the quick response - unfortunately, we do have a build issue on Ubuntu 20 - it is related to a GLIBC dependency.    Do you have the option to try to run on Ubuntu 22?   If nothing else, it would be good to confirm that the issue goes away.   It is on our hot priority list right now to down-level our build so it works on Ubuntu 20 - will keep you posted on that ....

**Comment by mupago** [comment]
@doberst Okay thanks, but the previous version of llmware seems to be working fine without issues on the same machine per my colleague. I will run few tests myself and will update here shortly.

**Comment by doberst** [comment]
@mupago - could you do a quick check on command line: ldd --version 

it will give the GLIBC version of the machine, likely 2.31 ?

**Comment by williamnadolski** [comment]
@doberst we could try building the glibc dependency from source, are you able to provide the specific version required (and a link to it, if possible)?

**Comment by doberst** [comment]
I believe it is GLIBC 2.35 ... we compiled our last build on Ubuntu 22, which brought that in as a version dependency.   We will build a down-level version in the next couple of days and get it out ...

**Comment by nadolsw** [comment]
Attempted to build GLIBC from source using the following:

sudo apt update
sudo apt install libc6
sudo apt install bison
sudo mkdir /downloads/glibc
sudo chmod 777 /downloads/glibc -R
sudo cd /downloads/glibc
sudo wget http://ftp.gnu.org/gnu/libc/glibc-2.35.tar.gz
sudo tar -xvzf glibc-2.35.tar.gz
sudo mkdir /downloads/glibc/glibc-2.35-install
sudo /downloads/glibc/glibc-2.35/configure --prefix=/downloads/glibc/glibc-2.35-install
sudo make
sudo make install
source ~/.bashrc

While it seemed to install GLIBC successfully, it did not resolve the PDF Parser error (perhaps just an env var resolution issue?).
However, reverting to llmware==0.1.15 did resolve the issue. Note, we were originally using ubuntu 20.04.1 with GLIBC 2.31

**Comment by WillWillWong** [comment]
2024/3/5,reverting to llmware==0.1.15 did resolve the issue.ldd (Ubuntu GLIBC 2.31-0ubuntu9.14) 2.31
Copyright (C) 2020 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。

**Comment by harveypitt** [comment]
@doberst I’m also experiencing this build issue. Is there any update on that down-level version?

**Comment by MacOS** [comment]
On this topic, may I suggest a change in the code base.

Currently, we have the following.
https://github.com/llmware-ai/llmware/blob/29647471d9cf64b7696e3186d0d2f6d10045269f/llmware/util.py#L131-L142

This is not optimal, since it does not tell the user what went wrong. It just says that it could not load the PDF parser, but not way. Also, it is not clear why the ``if`` is needed.

May I suggest the following change.

```python
try:                                                                                                  
    # attempt to load the shared library with ctypes                                                  
     _mod_pdf = cdll.LoadLibrary(_path_pdf)                                                                                                                                                                          
except Exception as e:                                                                                
    # catch error, if possible                                                                        
    logging.warning("warning: Module 'PDF Parser' could not be loaded from path - \n %s.\n"           
                                   "The following exceptions occured: %s",                                           
                                   _path_pdf, e)                                                                     
                                                                               
     raise ModuleNotFoundException("PDF Parser") 
```
While this is by far not ideal, it is an improvement as it tells the user **what** went wrong and **why**. In addition, the ``if`` statement is gone as well.

I'm happy to open a PR on that in the near future if people agree that this is a desirable.

**Comment by doberst** [comment]
@nadolsw, @harveypitt, @WillWillWong, @mupago, @Nuclear6, @MacOS - if you clone the latest repo, we have rebuilt the parser binaries for Ubuntu 20 support.   We have done the same for the GGUF libraries as well, so Ubuntu 20+ should be fully supported.   The key dependency is GLIBC (2.31 +).    Note, if you are using CUDA, the drivers should be 12.1+.   I am going to mark this issue closed - but if you are still experiencing issues on other flavors of Linux, please raise a new/separate ticket.   Also, would appreciate @MacOS recommendation + improvements on a more helpful exception handling ...
