### ISSUE TITLE
issue in installing the library in windows 10

### ISSUE THREAD

**Issue by tarek-kerbedj** [llmware-ai/llmware#50]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Oxidi\Desktop\gripenv\grip\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Oxidi\\AppData\\Local\\Temp\\pip-install-wem13w6j\\llmware_6ec9b6a58481432da47e8b764fdae30f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Oxidi\\AppData\\Local\\Temp\\pip-install-wem13w6j\\llmware_6ec9b6a58481432da47e8b764fdae30f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Oxidi\AppData\Local\Temp\pip-pip-egg-info-a2fj_bmk'
         cwd: C:\Users\Oxidi\AppData\Local\Temp\pip-install-wem13w6j\llmware_6ec9b6a58481432da47e8b764fdae30f\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Oxidi\AppData\Local\Temp\pip-install-wem13w6j\llmware_6ec9b6a58481432da47e8b764fdae30f\setup.py", line 61, in <module>
        long_description = readme_file.read()
      File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 8949: character maps to <undefined>

**Comment by turnham** [comment]
Hi, Yes llmware is not yet supported on Windows. It is on our near term roadmap and we hope to deliver it soon.
