### ISSUE TITLE
llmware.exceptions.ModelNotFoundException:

### ISSUE THREAD

**Issue by abhi-0907** [llmware-ai/llmware#614]
I have finetuned and quantized Lllama27b for domain specific task in gguf format. Can I use llmware for inferencing this type of gguf model from hugging face?? Because when I am trying to inference my model, I am getting this error:

Traceback (most recent call last):
  File "b:\Quantization_LLM\inference2.py", line 17, in <module>
    prompter = Prompt().load_model("abhiram973/MediTalk2-GGUF")
  File "B:\Quantization_LLM\myvenv\lib\site-packages\llmware\prompts.py", line 245, in load_model
    self.llm_model = self.model_catalog.load_model(gen_model, api_key=self.llm_model_api_key,
  File "B:\Quantization_LLM\myvenv\lib\site-packages\llmware\models.py", line 713, in load_model
    my_model = my_model.load_model_for_inference(loading_directions, model_card=model_card)
  File "B:\Quantization_LLM\myvenv\lib\site-packages\llmware\models.py", line 5204, in load_model_for_inference
    self._model = _LlamaModel(self._lib, path_model=self.model_path, params=self.model_params)
  File "B:\Quantization_LLM\myvenv\lib\site-packages\llmware\gguf_configs.py", line 681, in __init__
    raise ModelNotFoundException(path_model)
llmware.exceptions.ModelNotFoundException: 'C:\Users\abhir\llmware_data\model_repo\MediTalk2-GGUF\mediTalk_Q4_K_M.gguf' could not be located

And the code I used :

import time
import re

from llmware.models import ModelCatalog
from llmware.prompts import Prompt

ModelCatalog().register_gguf_model(model_name="abhiram973/MediTalk2-GGUF",
                                   gguf_model_repo="abhiram973/MediTalk2-GGUF",
                                   gguf_model_file_name="mediTalk_Q4_K_M.gguf",
                                   prompt_wrapper="my_version_inst")

ModelCatalog().register_new_finetune_wrapper(name="my_version_inst", main_start="<INST>",llm_start="</INST>")

prompter = Prompt().load_model("abhiram973/MediTalk2-GGUF")

question_list = ["I am having stomach pain and fever with little bit nausea?",
                 "My skin is itching after I sweated?"]

for i, entry in enumerate(question_list):
        
        start_time = time.time()
        print("\n")
        print(f"query - {i+1} - {entry['query']}")

        response = prompter.prompt_main(entry["query"])

        #print results
        time_taken = round(time.time()-start_time, 2)
        llm_response = re.sub("[\n\n]", "\n", response['llm_response'])
        print(f"llm_response - {i+1} - {llm_response}")
        print(f"time_taken - {i+1} - {time_taken}")

**Comment by doberst** [comment]
@abhi-0907 - thanks for sharing this.   Your code looks spot-on, and would expect this to work.   I have tested it locally, and can recreate the issue, e.g., I get the same error.   It looks as if the gguf engine is not loading the model successfully. Just confirming that it is a Llama-7b base model, and was converted/quantized using a current build of llama-cpp?   Any insights on the base model and the gguf build environment will definitely us to recreate the environment and figure out what is going wrong.

**Comment by abhi-0907** [comment]
Yeah, It was Llama2 - 7b basemodel and it was quantized using a current build of llama-cpp on windows.

**Comment by doberst** [comment]
@abhi-0907 - thanks for clarifying - we will dig in over the next couple of days and figure out what is going wrong.

**Comment by doberst** [comment]
@abhi-0907 - FYI, I have tried recompiling our llama cpp libs, and am still having trouble getting the Meditalk2 Q4_K_M file to successfully load. Not seeing an issue with other llama GGUF models in testing.  In experimenting, I re-quantized your original Pytorch meditalk model in Q4_K_M and it is working well (really nice finetuned output!) on both Mac and Windows CUDA.   Perhaps there is some small, but significant, difference in the llama cpp build you used to quantize (?). I have posted the re-quantized version in a private HF repo - I didn't want to put in a public repo unless you said OK ... please confirm that you are OK, and I will post it in llmware/bonchon - or can upload it to you directly if you prefer ...

**Comment by abhi-0907** [comment]
Thanks for resolving. You can post it on public repo.

**Comment by doberst** [comment]
@abhi-0907 - please check out the file posted on Huggingface:  
--repository:  llmware/bonchon 
--file:  meditalk_4_Q_M_042124.gguf

Hope that this resolves the issue.... 😄
