### ISSUE TITLE
segfault running rag.py

### ISSUE THREAD

**Issue by narimantos** [llmware-ai/llmware#69]
After watching the [video](https://www.youtube.com/watch?v=0naqpH93eEU) I wanted to give it a go. 

But was greeted with a segfault :( 

``` 
 python examples/rag.py

 > Creating library 'Agreements'...
[1]    20130 segmentation fault  python examples/rag.py
````

I happens somewhere in the `library.add_files(os.path.join(sample_files_path,"Agreements"))` line. 
tested with `Python 3.9.18`

**Comment by turnham** [comment]
Hi, yes see the discussion here for the fix/workaround: [https://github.com/llmware-ai/llmware/discussions/48](https://github.com/llmware-ai/llmware/discussions/48)

**Comment by turnham** [comment]
Sorry about that.   We don't see that in our testing.  I did a quick google and based on the answer here:
https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable 

Can you try adding this to your test code to see if that works around the issue (if so, we'll look at adding it to our initialization code):

```python
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

Also can you share some specifics on the system you are testing on and the output from:

```
uname -a
```

**Comment by turnham** [comment]
That looks like your system is maxed out in terms of running processes and can't even create a new thread to run docker compose kill.  Are you able to get a list of processes with ps or top and see if there are infact many processes running and kill some manually (or restart your WSL instance?)

**Comment by turnham** [comment]
Yes sorry I can't be of more help yet.  We've tested on native Linux (x86_64 and arm64) but have not had bandwidth yet to test on WSL.   So there may be something unique there going on that we haven't encountered yet. 

We are currently working on native Windows support and can add WSL testing/validation to the list of items.  Is there anything special about your self-compiled kernel or do you think testing on vanilla WSL2 should be sufficient?
