### ISSUE TITLE
problem with libzip4

### ISSUE THREAD

**Issue by juanluisrosaramos** [llmware-ai/llmware#76]
I wanted to try your software but I've found a problem during first execution. I work on a Ubuntu 20. 
apt install -y libxml2 libpng-dev libmongoc-dev libzip4 tesseract-ocr poppler-utils

E: Unable to locate package libzip4

So i wanted toimport your libraries but I 've found constantly problems with libzip4 library. In example,  in parsers.py
Traceback (most recent call last):
  File "parsers.py", line 67, in <module>
    _mod = cdll.LoadLibrary(_path_office)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libzip.so.4: cannot open shared object file: No such file or directory

Googling I couldn't find a solution to install properly libzip4

Thank you

**Comment by turnham** [comment]
Hi,
We are looking at making our native dependency management more robust and hope to deliver that by end of next week. In the meantime, the following should work get libzip4 installed on Ubuntu 20.  I just tested on fresh Ubuntu 20.4 instance and it worked for me:

```
echo deb http://archive.ubuntu.com/ubuntu/ bionic universe | sudo tee /etc/apt/sources.list.d/bionic.list
sudo apt update
sudo apt install -y libzip4
```

Also once you have libzip4 working, if you're running examples that do local file parsing, then you'll need to update the stack limit size to make sure the parsers can run:

```
ulimit -s 32768000
```

Let us know if you run into any other issues.

**Comment by doberst** [comment]
@juanluisrosaramos - if you pull the latest/recent updates, this issue should be resolved.   We ship a prebuilt shared library with all of the native dependencies included.   Please pull from the main branch, or pip install llmware==0.1.13.   If you have any problems, please raise another issue.

**Comment by hamnarif** [comment]
hello, i installed the library using pip install llmware but it's giving error
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], [line 1](vscode-notebook-cell:?execution_count=5&line=1)
----> [1](vscode-notebook-cell:?execution_count=5&line=1) from llmware.library import Library
      [2](vscode-notebook-cell:?execution_count=5&line=2) from llmware.retrieval import Query
      [3](vscode-notebook-cell:?execution_count=5&line=3) import time


ModuleNotFoundError: No module named 'llmware.library'; 'llmware' is not a package
