### ISSUE TITLE
Example scripts using llmware 

### ISSUE THREAD

**Issue by JessBerl** [llmware-ai/llmware#78]
We would love the communities help in building out our set of examples.  These can be anything from a comprehensive end to end RAG scenario to a discrete capability your using in the library.  

For developers looking for ways to contribute to llmware, this is a great first issue to get started.

**Comment by gongwork** [comment]
@JessBerl start learning `llmware` today, once up to speed, would like to help, Thanks

**Comment by doberst** [comment]
Closing original request as we have a wide base of examples today - will open up new issues for specific example types.
