### ISSUE TITLE
Query about other LLM

### ISSUE THREAD

**Issue by MuhammadNizamani** [llmware-ai/llmware#79]
Hello everyone !
I don't have chatgpt 4 api key 
can I use other then chatgpt  like. I want to use open source LLM like  makersuit from google ?
I want to contribute in your project 
Thanks

**Comment by JessBerl** [comment]
Hi @MuhammadNizamani - in addition to OpenAI, llmware has support for Google PaLM, Anthropic Claude and AI21 Jurassic models which offer free API keys for developers to use.  Please take a look at the working_with_llms.py. 

We also support using the open source models on Hugging Face.  Please see the example huggingface_integration.py that includes some of the smaller models that can run locally on a laptop.  

If you have questions as you work thru these examples, please post them in our [discussions board](https://github.com/llmware-ai/llmware/discussions).
