### ISSUE TITLE
[MINOR] Update botocore version

### ISSUE THREAD

**Issue by perinm** [llmware-ai/llmware#816]
llmware is requiring botocore-1.27.96, which is very old and causes inconsistencies with other projects.

remove version restriction or update it to latest one botocore-1.34.106

![image](https://github.com/llmware-ai/llmware/assets/26926409/b0696c01-88e2-44c7-a057-48101f94461f)

**Comment by doberst** [comment]
@perinm - thanks for flagging this and agree 100% - we will update the requirement (will do a little testing first to confirm no issues), but should be updated in the next 24-48 hours - and will be in the next pip install release by end of week.

**Comment by doberst** [comment]
@perinm - thanks again - merged into the requirements.txt and setup.py - and will be reflected in the next pip package.
