### ISSUE TITLE
ReRanker model : register new model into the ModelCatalog()

### ISSUE THREAD

**Issue by arcontechnologies** [llmware-ai/llmware#916]
Hi,

**This is not an issue** but llmware is little bit cryptic when working with model that are not part of the modelCatalog. 

As far as I can see, there are jinaai reranker models : turbo_en and tiny_en in the modelCatalog.
I want to load a new one in the modelCatalog.
Can someone show me how to proceed. I'm new to llmware api.

I tried this but it said `llmware.exceptions.ModelNotFoundException: 'jinaai/jina-reranker-v2-base-multilingual' could not be located`

```
LLMWareConfig.set_home("D:\\path-to-llmware_data_folder\\")  # where under` jina-reranker-v2-base-multilingual `folder I put the model
hf_model_name = "jinaai/jina-reranker-v2-base-multilingual"
os.environ["HF_TOKEN"] = "my_hf_token"
ModelCatalog().register_new_model_card.register_sentence_transformer_model(model_name=hf_model_name,embedding_dims=384,context_window=8192,link="https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual",display_name="jina-reranker-v2-base-multilingual")
reranker_model = ModelCatalog().load_model("jina-reranker-v2-base-multilingual")
```

Any insight

**Comment by doberst** [comment]
@arcontechnologies - thanks for the message and sorry that you ran into this issue.   Generally, just about any model from HF can be used in llmware, but it requires a single one line step first to 'register' the model in the llmware ModelCatalog- and then once registered, the model can be used in a first-tier way just by referencing the model_name.    For the general case with HF, [please look here](https://github.com/llmware-ai/llmware/blob/61dc3b45a31699a617c3c342ab16be7142ac5492/llmware/models.py#L516).   

The Jina Reranker is a new capability - to add a Jina model, you can add a new model card as follows:  

```python
   
# fill in the dictionary entry with the relevant details - hopefully straightforward

  my_new_jina_model = {"model_name": 'my_favorite_jina_model', "display_name": "jina-multi",
  "model_family": "HFReRankerModel",
  "model_category": "reranker", "model_location": "hf_repo", "embedding_dims": 384, "context_window": 8192,
  "link": "https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual", "custom_model_files": [],
  "custom_model_repo": ""
  "hf_repo": "jinaai/jina-reranker-v2-base-multilingual"}

ModelCatalog().register_new_model_card(my_new_jina_model)
```

Once you complete that step, you can use the model with .load_model("my_favorite_jina_model") -> the most important attributes to get right are the hf repo, embedding dims and context window.

Hope that makes sense - and please ping back with any questions/clarifications.

**Comment by arcontechnologies** [comment]
@doberst  Thank you so much for the quick answer. I'll follow the instructions.
